[theme]
primaryColor = "#0E7C7B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6F8"
textColor = "#13293D"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
